### ISSUE TITLE
Terricreus

### ISSUE THREAD

**Issue by Betah** [Prodigy4532/Prodigy4532XML#1]
Can you help me porting this map to CardinalPGM?

https://github.com/twizmwazin/CardinalPGM/issues/976

**Comment by xFracTV** [comment]
Whats happend with this XML? what regions are bad?

**Comment by Betah** [comment]
All regions, because are coded on 1.4.0 and Cardinal only support 1.3.6

**Comment by xFracTV** [comment]
Ok

**Comment by xFracTV** [comment]
ATM i fixed the kits and wool monument. https://github.com/xFracTV/xFracTVXML/commit/40cb15b86350d47848c006d3c54d4da38cb74a06

Im working in the regions.

**Comment by Betah** [comment]
Thanks <3

**Comment by Betah** [comment]
Could you finish the regions?

**Comment by xFracTV** [comment]
Shit, I forgot it XD

**Comment by Betah** [comment]
Ye, I see

**Comment by xFracTV** [comment]
try the map with the 1.9 but with my kits.

**Comment by Prodigy4532** [comment]
https://github.com/Prodigy4532/Prodigy4532XML/commit/8eba162ceb9a05ec30973d6b4172b5c0ba79a671
